version: '3'

services:
  cassandra-node1:
    image: cassandra:3.11.6
    ports:
      - 9042:9042
    environment:
      CASSANDRA_SEEDS: cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - cassandra-data-node1:/var/lib/cassandra

  cassandra-node2:
    image: cassandra:3.11.6
    ports:
      - 9043:9042
    environment:
      CASSANDRA_SEEDS: cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - cassandra-data-node2:/var/lib/cassandra

  cassandra-node3:
    image: cassandra:3.11.6
    ports:
      - 9044:9042
    environment:
      CASSANDRA_SEEDS: cassandra-node1,cassandra-node2,cassandra-node3
    volumes:
      - cassandra-data-node3:/var/lib/cassandra

volumes:
  cassandra-data-node1:
  cassandra-data-node2:
  cassandra-data-node3: