version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: circle-of-friends-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: circle-of-friends2_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d circle-of-friends2_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: