version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=cats-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    ports:
      - "9042:9042"
    volumes:
      - node1-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u cassandra -p cassandra -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 10

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=cats-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    depends_on:
      cassandra-node1:
        condition: service_healthy
    volumes:
      - node2-data:/var/lib/cassandra

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=cats-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    depends_on:
      cassandra-node1:
        condition: service_healthy
    volumes:
      - node3-data:/var/lib/cassandra

volumes:
  node1-data:
  node2-data:
  node3-data: