global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring_apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        'host.docker.internal:8081', # account-user-service
        'host.docker.internal:8082', # admin-service
        'host.docker.internal:8083', # analytics-service
        'host.docker.internal:8084', # auth-service
        'host.docker.internal:8085', # group-chats-service
        'host.docker.internal:8086', # messages-service
        'host.docker.internal:8087', # notifications-service
        'host.docker.internal:8088', # posts-user-service
        'host.docker.internal:8089'  # registry-service
      ]