spring:
  application:
    name: posts-user-service

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  access:
    jwt:
      expiration: ${ACCESS_JWT_EXPIRATION}
  refresh:
    jwt:
      expiration: ${REFRESH_JWT_EXPIRATION}

service:
  jwt:
    secret: ${SERVICE_JWT_SECRET}

interservice:
  secret:
    key: ${INTERSERVICE_SECRET_KEY}
  header:
    name: ${INTERSERVICE_HEADER_NAME}

registry:
  service:
    url: ${REGISTRY_SERVICE_URL}

myplug: ${TOKEN_PLUG}
mysecret: ${MY_SECRET}

grpc:
  client:
    tokenRefreshRegistryService:
      address: localhost:9090
      negotiationType: plaintext

yandex:
  token: ${YANDEX_TOKEN}
